plugins {
    id 'java'
}

group = 'ru.netology'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'com.codeborne:selenide:7.3.3'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'io.cucumber:cucumber-java:7.18.0'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.18.0'
    testImplementation 'org.junit.platform:junit-platform-suite:1.10.2'
}

test {
    useJUnitPlatform()
    include '**/RunCucumberTest.class'
    systemProperty 'selenide.headless', System.getProperty('selenide.headless')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
